
package Vista;

import Logica.*;
import static Logica.Proceso.BLOQUEADO;
import static Logica.Proceso.EJECUCION;
import static Logica.Proceso.LISTO;
import javax.swing.table.DefaultTableModel;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
public class Simulador extends javax.swing.JFrame implements ActionListener{

    DefaultTableModel modelo;
    DefaultTableModel modelo1;
    DefaultTableModel modelo2;
    DefaultTableModel modelo3;
    DefaultTableModel modelo4;
    ListaProceso l;
    int delay = 1000; //milliseconds
    int procesos=1;
    int tiempo=0;
    int numP = 1;
    Timer temporizador;
    
    
    
    
    public Simulador() {
        initComponents();
        String cabecera[]={"Proceso","Memoria"};
        String datos[] []={};
        String cabecera1[]={"Proceso","Memoria","Tiempo"};
        String datos1[] []={};
        String cabecera2[]={"Proceso","Memoria","Tiempo"};
        String datos2[] []={};
        String cabecera3[]={"Proceso","Tiempo"};
        String datos3[] []={};
        String cabecera4[]={"Proceso","Tiempo"};
        String datos4[] []={};
        modelo=new DefaultTableModel(datos,cabecera);
        modelo1=new DefaultTableModel(datos1,cabecera1);
        modelo2=new DefaultTableModel(datos2,cabecera2);
        modelo3=new DefaultTableModel(datos3,cabecera3);
        modelo4=new DefaultTableModel(datos4,cabecera4);
        tablaprocesos.setModel(modelo);
        tablaEspera.setModel(modelo1);
        tablaEjecutar.setModel(modelo2);
        tablaBloqueado.setModel(modelo3);
        tablaTerminado.setModel(modelo4);
        l = new ListaProceso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfrmProcesos = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmemoria = new javax.swing.JTextField();
        btnagregarproceso = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrioridad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        recurso1 = new javax.swing.JCheckBox();
        recurso2 = new javax.swing.JCheckBox();
        recurso3 = new javax.swing.JCheckBox();
        jfrmEjecutar = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEspera = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEjecutar = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTerminado = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnejecutar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaBloqueado = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaprocesos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumprocesos = new javax.swing.JTextField();
        btnnumprocesos = new javax.swing.JButton();

        jfrmProcesos.setMaximizedBounds(new java.awt.Rectangle(525, 380, 380, 380));
        jfrmProcesos.setMinimumSize(new java.awt.Dimension(280, 380));

        jLabel4.setText("Memoria(KB)");

        jLabel7.setText("Recursos");

        txtmemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmemoriaActionPerformed(evt);
            }
        });

        btnagregarproceso.setText("Agregar");
        btnagregarproceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarprocesoActionPerformed(evt);
            }
        });

        jLabel11.setText("Id");

        jLabel12.setText("Nombre");

        jLabel13.setText("Prioridad");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrioridadActionPerformed(evt);
            }
        });

        jLabel14.setText("Procesos");

        recurso1.setText("Recurso1");
        recurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurso1ActionPerformed(evt);
            }
        });

        recurso2.setText("Recurso2");
        recurso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurso2ActionPerformed(evt);
            }
        });

        recurso3.setText("Recurso3");

        javax.swing.GroupLayout jfrmProcesosLayout = new javax.swing.GroupLayout(jfrmProcesos.getContentPane());
        jfrmProcesos.getContentPane().setLayout(jfrmProcesosLayout);
        jfrmProcesosLayout.setHorizontalGroup(
            jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmProcesosLayout.createSequentialGroup()
                .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfrmProcesosLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3))
                    .addGroup(jfrmProcesosLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnagregarproceso)
                            .addGroup(jfrmProcesosLayout.createSequentialGroup()
                                .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmProcesosLayout.createSequentialGroup()
                                        .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jfrmProcesosLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(26, 26, 26)))
                                .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombre)
                                        .addComponent(txtPrioridad)
                                        .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(txtmemoria))
                                    .addComponent(recurso1)
                                    .addComponent(recurso2)
                                    .addComponent(recurso3))
                                .addGap(12, 12, 12))))
                    .addGroup(jfrmProcesosLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel14)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jfrmProcesosLayout.setVerticalGroup(
            jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jfrmProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(recurso1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recurso2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recurso3)
                .addGap(29, 29, 29)
                .addComponent(btnagregarproceso)
                .addGap(111, 111, 111))
        );

        jfrmEjecutar.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jfrmEjecutar.setMinimumSize(new java.awt.Dimension(750, 650));

        tablaEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaEspera);

        jLabel8.setText("Listo");

        tablaEjecutar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaEjecutar);

        jLabel9.setText("Ejecucion");

        tablaTerminado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaTerminado);

        jLabel10.setText("Procesos Terminados");

        btnejecutar.setText("Ejecutar");
        btnejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejecutarActionPerformed(evt);
            }
        });

        tablaBloqueado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablaBloqueado);

        jLabel5.setText("Bloqueado");

        tablaprocesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaprocesos);

        jButton1.setText("Parar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nuevo");

        javax.swing.GroupLayout jfrmEjecutarLayout = new javax.swing.GroupLayout(jfrmEjecutar.getContentPane());
        jfrmEjecutar.getContentPane().setLayout(jfrmEjecutarLayout);
        jfrmEjecutarLayout.setHorizontalGroup(
            jfrmEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmEjecutarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfrmEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addGroup(jfrmEjecutarLayout.createSequentialGroup()
                        .addGroup(jfrmEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jfrmEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jfrmEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jfrmEjecutarLayout.createSequentialGroup()
                        .addComponent(btnejecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel6))
                .addGap(0, 576, Short.MAX_VALUE))
        );
        jfrmEjecutarLayout.setVerticalGroup(
            jfrmEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmEjecutarLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jfrmEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jfrmEjecutarLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jfrmEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jfrmEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnejecutar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Simulador de Procesos");

        jLabel2.setText("Digite la cantidad de Procesos a evaluar");

        txtnumprocesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumprocesosActionPerformed(evt);
            }
        });

        btnnumprocesos.setText("Aceptar");
        btnnumprocesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumprocesosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnumprocesos)
                            .addComponent(btnnumprocesos, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(txtnumprocesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnnumprocesos)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumprocesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumprocesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumprocesosActionPerformed

    private void btnnumprocesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumprocesosActionPerformed
        
        jfrmProcesos.setVisible(true);
        jfrmProcesos.setLocationRelativeTo(null);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnnumprocesosActionPerformed

    private void btnagregarprocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarprocesoActionPerformed

        int numprocesos=Integer.parseInt(txtnumprocesos.getText());
   
        String memoria=txtmemoria.getText();
        String recurso="";
        

        l.aProceso(Integer.parseInt(memoria), procesos, recurso);
        
        Object datos[]={l.procesos.get(procesos-1).vNombre(),memoria,recurso};
        modelo.addRow(datos);

        txtmemoria.setText("");


        if (modelo.getRowCount()==numprocesos){

            jfrmEjecutar.setVisible(true);
            jfrmEjecutar.setLocationRelativeTo(null);
            jfrmProcesos.setVisible(false);
        }
            
        procesos++;
    }//GEN-LAST:event_btnagregarprocesoActionPerformed

    private void txtmemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemoriaActionPerformed
    @Override
    public void actionPerformed(ActionEvent e) {
        int tmProc;
        l.cambiarEstProceso(tiempo+1, numP);
        tmProc = 0;
        for (Proceso pro : l.procesos){
            if(tiempo < tmProc)
                continue;
            if(pro.vEstado() == LISTO ){
                Object datos1[]={pro.vNombre(),pro.vTamanio(),tiempo};
                modelo1.addRow(datos1);
            }else if(pro.vEstado() == EJECUCION){
                Object datos2[]={pro.vNombre(),pro.vTamanio(),tiempo};
                modelo2.addRow(datos2);
                if(pro.completo()){
                    Object datos4[]={pro.vNombre(),tiempo};
                    modelo4.addRow(datos4);
                }
            }else if(pro.vEstado() == BLOQUEADO ){
                Object dato3[]={pro.vNombre(),tiempo};
                modelo2.addRow(dato3);
                modelo3.addRow(dato3);
            }
            tmProc++;
        }
        tiempo++;
        if(numP == l.procesos.size())
            numP=1;
        else
            numP++;
        if(l.termina()){
            System.out.println("acabo");
            temporizador.stop();
            return;
        }else
            temporizador.restart();
            
    }
    private void btnejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejecutarActionPerformed
        temporizador = new Timer(delay, this);
        temporizador.start();
        
    }//GEN-LAST:event_btnejecutarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrioridadActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void recurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recurso1ActionPerformed

    private void recurso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recurso2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarproceso;
    private javax.swing.JButton btnejecutar;
    private javax.swing.JButton btnnumprocesos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JFrame jfrmEjecutar;
    private javax.swing.JFrame jfrmProcesos;
    private javax.swing.JCheckBox recurso1;
    private javax.swing.JCheckBox recurso2;
    private javax.swing.JCheckBox recurso3;
    private javax.swing.JTable tablaBloqueado;
    private javax.swing.JTable tablaEjecutar;
    private javax.swing.JTable tablaEspera;
    private javax.swing.JTable tablaTerminado;
    private javax.swing.JTable tablaprocesos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrioridad;
    private javax.swing.JTextField txtmemoria;
    private javax.swing.JTextField txtnumprocesos;
    // End of variables declaration//GEN-END:variables
}
